[[venues]]
name = "BINANCE"
oms_type = "NETTING"
account_type = "MARGIN"
base_currency = "USDT"
starting_balances = ["1_000_000 USDT"]

[[data]]
catalog_path = "./data/ETHUSDT.BINANCE/catalog"
data_cls = "Klines"
instrument_id = "ETHUSDT.BINANCE"
start_time = "2024-01-01T00:00:00"
end_time = "2024-12-01T00:00:00"

[[strategies]]
strategy_path = "strategies.rsi_mean_reversion:RsiMeanReversion"
config_path = "strategies.rsi_mean_reversion:RsiMeanReversionConfig"

[strategies.config]
instrument_id = "ETHUSDT.BINANCE"
base_currency = "ETH"
quote_currency = "USDT"
venue = "BINANCE"
bar_type = "ETHUSDT.BINANCE-1-HOUR-LAST-INTERNAL@1-MINUTE-EXTERNAL"
#bar_type = "ETHUSDT.BINANCE-1-MINUTE-LAST-EXTERNAL"
max_position_ratio = 1.0
enable_redis = true
max_period = 100000

[analysis]
output_path = "./reports"
file_prefix = "rsi_mean_reversion_eth_backtest"
venues = ["BINANCE"]
